name: CI Build Check macOS aarch64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install R
        run: |
          curl -o R-Portable.pkg https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.2.0-arm64.pkg
          mkdir -p /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/
          sudo installer -pkg R-Portable.pkg -target /
          sudo mv /Library/Frameworks/R.framework /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/

      - name: List directory contents for debugging
        run: ls /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/R.framework/

      - name: Install R packages
        run: /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/R.framework/Versions/4.2-arm64/bin/Rscript app/scripts/install_packages.R

      - name: Download standalone Python 3.10
        run: |
          curl -L -o python-3.10.15-standalone.tar.gz https://github.com/indygreg/python-build-standalone/releases/download/20240909/cpython-3.10.15+20240909-aarch64-apple-darwin-install_only.tar.gz
          mkdir -p /Users/runner/work/cauldron/cauldron/app/bin/darwin/python
          tar -xzf python-3.10.15-standalone.tar.gz -C /Users/runner/work/cauldron/cauldron/app/bin/darwin/python

      - name: List directory contents for debugging
        run: ls app/bin/mac/python

      - name: Validate R_HOME environment variable
        env:
          R_HOME: /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
        shell: bash
        run: |
          if [ -z "$R_HOME" ]; then
            echo "R_HOME is not set"
            exit 1
          else
            echo "R_HOME is set to $R_HOME"
            ls $R_HOME
          fi

      - name: Install Python packages
        env:
          R_HOME: /Users/runner/work/cauldron/cauldron/app/bin/darwin/R-Portable/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
        run: |
          /Users/runner/work/cauldron/cauldron/app/bin/darwin/python/bin/python3.10 -m pip install -r app/requirements.txt

      - name: Validate Python installation
        run: |
          /Users/runner/work/cauldron/cauldron/app/bin/darwin/python/bin/python3.10 -m pip --version
          /Users/runner/work/cauldron/cauldron/app/bin/darwin/python/bin/python3.10 -m pip list

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: |
          npm run build:prod
          electron-builder build --mac --arm64 --publish=never

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=VERSION::$(node -p -e "require('./package.json').version")"
