name: Build and Release R and Python-Portable For Windows x64

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Get version from package.json
      id: get_version
      run: echo "::set-output name=VERSION::$(node -p -e "require('./package.json').version")"

    - name: Install R
      run: |
        Invoke-WebRequest -Uri https://cran.r-project.org/bin/windows/base/old/4.4.1/R-4.4.1-win.exe -OutFile R-Portable.exe
        New-Item -ItemType Directory -Force -Path app/bin/win/R-Portable
        Start-Process -FilePath R-Portable.exe -ArgumentList "/VERYSILENT", "/DIR=app/bin/win/R-Portable" -Wait

    - name: Install R packages
      env:
        R_LIBS_USER: ${{ github.workspace }}/app/bin/win/R-Portable/library
      run: Rscript app/scripts/install_packages.R

    - name: Download standalone Python 3.10
      run: |
        Invoke-WebRequest -Uri https://github.com/indygreg/python-build-standalone/releases/download/20240107/cpython-3.10.13+20240107-x86_64-pc-windows-msvc-shared-install_only.tar.gz -OutFile python-3.10.13-standalone.tar.gz
        New-Item -ItemType Directory -Force -Path app/bin/win/python
        tar -xzf python-3.10.13-standalone.tar.gz -C app/bin/win

    - name: Install Python packages
      env:
        R_HOME: ${{ github.workspace }}/app/bin/win/R-Portable
      run: |
        cmd /c ${{ github.workspace }}/app/bin/win/python/python.exe -m pip install -r app/requirements.txt

    - name: Rename app to resources
      run: |
        mv app resources

    - name: Compress Python directory
      run: tar -czf python.tar.gz resources/bin/win/python

    - name: Compress R-Portable directory
      run: tar -czf r-portable.tar.gz resources/bin/win/R-Portable

    - name: Upload Python Archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has `repo` scope
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: python.tar.gz
        asset_name: python-win-x86_64-extra.tar.gz
        asset_content_type: application/tar+gzip

    - name: Upload R-Portable Archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token has `repo` scope
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: r-portable.tar.gz
        asset_name: r-portable-win-x86_64-extra.tar.gz
        asset_content_type: application/tar+gzip
