name: Setup macOS Environment

on:
    workflow_call:
        inputs:
            os:
                description: 'Operating System'
                required: true
                default: 'macos-latest'
                type: string
            arch:
                description: 'Architecture'
                required: true
                default: 'arm64'
                type: string

jobs:
  setup_macOS_environment:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
          brew update
          brew install --cask xquartz
          brew install gfortran pkg-config libpng jpeg xz pcre2 curl harfbuzz fribidi libx11 libxext libxrender libxtst cairo

      - name: Add Homebrew to PATH
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Set up PATH
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
