name: Setup Linux Environment

on:
    workflow_call:
        inputs:
            os:
                description: 'Operating System'
                required: true
                default: 'ubuntu-latest'
                type: string
            arch:
                description: 'Architecture'
                required: true
                default: 'x64'
                type: string

jobs:
  setup_macOS_environment:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libopenjp2-tools
          sudo apt-get install -y build-essential libreadline-dev libx11-dev libxt-dev libpng-dev libjpeg-dev libcairo2-dev libbz2-dev libzstd-dev liblzma-dev libcurl4-openssl-dev libssl-dev libxml2-dev gfortran

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
