name: Test Build For Unix x64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libreadline-dev libx11-dev libxt-dev libpng-dev libjpeg-dev libcairo2-dev libbz2-dev libzstd-dev liblzma-dev libcurl4-openssl-dev libssl-dev libxml2-dev gfortran

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install R
      run: |
        wget https://cran.r-project.org/src/base/R-4/R-4.4.1.tar.gz
        mkdir -p app/bin/linux/R-Portable
        tar -xzvf R-4.4.1.tar.gz
        cd R-4.4.1
        ./configure --prefix=${{ github.workspace }}/app/bin/linux/R-Portable/ --enable-R-shlib --with-blas --with-lapack
        make
        make install
        R --version

    - name: Set up R R_LIBS_USER
      run: |
        echo "R_LIBS_USER=${{ github.workspace }}/app/bin/linux/R-Portable/library" >> $GITHUB_ENV

    - name: Install R packages
      run: Rscript app/scripts/install_packages.R
