name: Test build R for macOS arm64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
          brew update
          brew install --cask xquartz
          brew install gfortran pkg-config libpng jpeg xz pcre2 curl harfbuzz fribidi libx11 libxext libxrender libxtst cairo
#
      - name: Add Homebrew to PATH
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH
#
      - name: Set up PATH
        run: |
          echo "$(brew --prefix gcc)/bin" >> $GITHUB_PATH
#
#      - name: Download R and Compile R
#        env:
#          CPPFLAGS: -I/opt/X11/include
#          LDFLAGS: -L/opt/X11/lib
#        run: |
#          curl -O https://cran.r-project.org/src/base/R-4/R-4.4.1.tar.gz
#          mkdir -p app/bin/linux/R-Portable
#          tar -xzvf R-4.4.1.tar.gz
#          cd R-4.4.1
#          ./configure --prefix=${{ github.workspace }}/app/bin/darwin/R-Portable/ --enable-R-shlib --with-blas --with-lapack --with-aqua --with-x
#          make -j$(nproc)
#          make install
#          R --version

      - name: Get and compile R base dependency
        env:
          CPPFLAGS: -I/opt/X11/include
          LDFLAGS: -L/opt/X11/lib
        run: |
          git clone https://github.com/R-macos/recipes.git
          mkdir -p app/bin/linux/R-Portable
          cd recipes

          export PREFIX="${{ github.workspace }}/R/arm64"
          ./build.sh r-base-dev

      - name: List files
        run: ls "${{ github.workspace }}/R/arm64"

      - name: Add compiled dependencies to PATH
        run: echo "${{ github.workspace }}/R/arm64" >> $GITHUB_PATH

      - name: Compile R
        env:
          CPPFLAGS: -I/opt/homebrew/include
        run: |
          curl -O https://cran.r-project.org/src/base/R-4/R-4.4.1.tar.gz
          tar -xzvf R-4.4.1.tar.gz
          cd R-4.4.1
          ./configure --prefix=${{ github.workspace }}/app/bin/darwin/R-Portable/ --enable-R-shlib --with-blas --with-lapack
          make -j$(nproc)
          make install


      - name: List files
        run: ls app/bin/linux/R-Portable/

      - name: Set up writable permissions for R library
        run: |
          chmod -R 777 ${{ github.workspace }}/app/bin/linux/R-Portable/lib

      - name: Set up R R_LIBS_USER
        run: |
          echo "R_LIBS_USER=${{ github.workspace }}/app/bin/linux/R-Portable/lib" >> $GITHUB_ENV

      - name: Install R packages
        run: Rscript app/scripts/install_packages.R
